### ISSUE TITLE
omikron is not too happy about exceptions

### ISSUE THREAD

**Issue by mathiasverraes** [turanct/omikron#4]
``` php
<?php
function bad() { throw new \Exception("Something");}
return
within("X",
    describe("Y",
        it("Z", function(){ return
            expect(
                bad(),
            toBe(
                "ok"
            ));
        })
    )
);
```

output:

```
PHP Warning:  array_map(): An error occurred while invoking the map callback in vendor/turanct/omikron/src/input.php on line 40
PHP Stack trace:
PHP   1. {main}() vendor/turanct/omikron/bin/omikron:0
PHP   2. getTopics() vendor/turanct/omikron/bin/omikron:30
PHP   3. array_map() vendor/turanct/omikron/src/input.php:40

Warning: array_map(): An error occurred while invoking the map callback in vendor/turanct/omikron/src/input.php on line 40

Call Stack:
    0.0002     235352   1. {main}() vendor/turanct/omikron/bin/omikron:0
    0.0015     367312   2. getTopics() vendor/turanct/omikron/bin/omikron:30
    0.0016     368144   3. array_map() vendor/turanct/omikron/src/input.php:40

PHP Fatal error:  Uncaught exception 'Exception' with message 'Something' in topics/topic-Day.php:3
Stack trace:
#0 topics/topic-Day.php(9): bad()
#1 vendor/turanct/omikron/src/omikron.php(50): {closure}()
#2 topics/topic-Day.php(13): it('Z', Object(Closure))
#3 vendor/turanct/omikron/src/input.php(37): include('/Users/mathias/...')
#4 [internal function]: {closure}('/Users/mathias/...')
#5 vendor/turanct/omikron/src/input.php(40): array_map(Object(Closure), Array)
#6 vendor/turanct/omikron/bin/omikron(30): getTopics(Array)
#7 {main}
  thrown in topics/topic-Day.php on line 3

Fatal error: Uncaught exception 'Exception' with message 'Something' in topics/topic-Day.php on line 3

Exception: Something in topics/topic-Day.php on line 3

Call Stack:
    0.0002     235352   1. {main}() vendor/turanct/omikron/bin/omikron:0
    0.0015     367312   2. getTopics() vendor/turanct/omikron/bin/omikron:30
    0.0016     368144   3. array_map() vendor/turanct/omikron/src/input.php:40
    0.0016     368712   4. {closure:vendor/turanct/omikron/src/input.php:36-38}() vendor/turanct/omikron/src/input.php:40
    0.0016     372872   5. include('topics/topic-Day.php') vendor/turanct/omikron/src/input.php:37
    0.0016     373376   6. it() topics/topic-Day.php:13
    0.0016     373416   7. {closure:topics/topic-Day.php:7-13}() vendor/turanct/omikron/src/omikron.php:50
    0.0016     373448   8. bad() topics/topic-Day.php:9
```

**Comment by mathiasverraes** [comment]
Expected 

```
topics: 1
features: 1
assertions: 1

FAILED: X: Y Z

Exception: Something in topics/topic-Day.php on line 3

Call Stack:
    0.0002     235352   1. {main}() vendor/turanct/omikron/bin/omikron:0
    0.0015     367312   2. getTopics() vendor/turanct/omikron/bin/omikron:30
    0.0016     368144   3. array_map() vendor/turanct/omikron/src/input.php:40
    0.0016     368712   4. {closure:vendor/turanct/omikron/src/input.php:36-38}() vendor/turanct/omikron/src/input.php:40
    0.0016     372872   5. include('topics/topic-Day.php') vendor/turanct/omikron/src/input.php:37
    0.0016     373376   6. it() topics/topic-Day.php:13
    0.0016     373416   7. {closure:topics/topic-Day.php:7-13}() vendor/turanct/omikron/src/omikron.php:50
    0.0016     373448   8. bad() topics/topic-Day.php:9

```

**Comment by turanct** [comment]
nice! will fix tomorrow :camel:

**Comment by turanct** [comment]
version 0.6.0 was released with this functionality
